<?php
/**
 * 测试发送邮件
 * 访问: https://faka.opwan.ai/test_send_email.php?to=邮箱地址
 */

require __DIR__.'/../vendor/autoload.php';
$app = require_once __DIR__.'/../bootstrap/app.php';
$app->make('Illuminate\Contracts\Console\Kernel')->bootstrap();

header('Content-Type: text/plain; charset=utf-8');

$to = $_GET['to'] ?? '';

if (empty($to)) {
    echo "使用方法:\n";
    echo "https://faka.opwan.ai/test_send_email.php?to=your@email.com\n\n";
    echo "这将发送一封测试邮件到指定邮箱\n";
    exit;
}

if (!filter_var($to, FILTER_VALIDATE_EMAIL)) {
    echo "❌ 邮箱格式不正确: {$to}\n";
    exit;
}

echo "=== 测试发送邮件 ===\n\n";
echo "收件人: {$to}\n";
echo "发件人: " . config('mail.from.address') . " (" . config('mail.from.name') . ")\n";
echo "SMTP服务器: " . config('mail.host') . ":" . config('mail.port') . "\n\n";

try {
    $testTime = date('Y-m-d H:i:s');
    $subject = '【测试邮件】独角数卡邮件系统测试';
    $body = <<<HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
</head>
<body style="font-family: Arial, sans-serif; padding: 20px;">
    <h2 style="color: #333;">邮件系统测试</h2>
    <p>这是一封测试邮件，用于验证独角数卡邮件系统是否正常工作。</p>

    <div style="background: #f5f5f5; padding: 15px; border-radius: 5px; margin: 20px 0;">
        <p><strong>测试信息:</strong></p>
        <ul>
            <li>发送时间: {$testTime}</li>
            <li>收件人: {$to}</li>
            <li>SMTP服务器: {host}:{port}</li>
            <li>加密方式: {encryption}</li>
        </ul>
    </div>

    <p style="color: #666;">如果您收到这封邮件，说明邮件系统配置正确，可以正常发送邮件。</p>

    <hr style="border: none; border-top: 1px solid #ddd; margin: 20px 0;">
    <p style="font-size: 12px; color: #999;">
        这是系统自动发送的测试邮件，请勿回复。<br>
        Generated by Claude Code
    </p>
</body>
</html>
HTML;

    $body = str_replace(['{host}', '{port}', '{encryption}'], [
        config('mail.host'),
        config('mail.port'),
        config('mail.encryption')
    ], $body);

    echo "=== 发送邮件... ===\n\n";

    // 方式1: 使用 Mail::send（同步发送）
    \Illuminate\Support\Facades\Mail::send(
        ['html' => 'email.mail'],
        ['body' => $body],
        function ($message) use ($to, $subject) {
            $message->to($to)->subject($subject);
        }
    );

    echo "✅ 邮件发送成功！\n\n";
    echo "请检查邮箱: {$to}\n";
    echo "- 查看收件箱\n";
    echo "- 查看垃圾邮件箱\n";
    echo "- 如果使用Gmail，查看 Promotions 或 Updates 标签\n\n";

    echo "如果收到邮件，说明邮件系统配置正确！\n";
    echo "如果没收到，请检查:\n";
    echo "1. SMTP配置是否正确\n";
    echo "2. SMTP服务器是否允许从当前服务器发送\n";
    echo "3. 查看 Railway 日志中的错误信息\n";

} catch (\Exception $e) {
    echo "❌ 邮件发送失败！\n\n";
    echo "错误信息: " . $e->getMessage() . "\n\n";
    echo "详细错误:\n";
    echo $e->getTraceAsString() . "\n\n";

    echo "可能的原因:\n";
    echo "1. SMTP服务器连接失败（检查host、port、encryption）\n";
    echo "2. SMTP认证失败（检查username、password）\n";
    echo "3. 发件地址未授权（检查from.address）\n";
    echo "4. 网络连接问题（Railway → Resend SMTP）\n\n";

    echo "建议:\n";
    echo "1. 访问 https://faka.opwan.ai/check_email_system.php 检查配置\n";
    echo "2. 查看 Railway 实时日志\n";
    echo "3. 检查 Resend 后台是否有发送记录\n";
}
